version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: